### ISSUE TITLE
Feature: local enums def file

### ISSUE THREAD

**Issue by joshball** [risenforces/nestjs-zod-prisma#1]
Any interest in adding this to your library?
https://github.com/CarterGrimmeisen/zod-prisma/pull/111

solves this problem: https://github.com/CarterGrimmeisen/zod-prisma/issues/108

**Comment by risenforces** [comment]
@joshball Thanks, I'll check it soon

**Comment by risenforces** [comment]
@joshball Added in #2 (`v1.1.0` version)
